import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Nhóm Đồ Án Twofish",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-blue-500 to-purple-600 min-h-screen text-white">
        {/* Menu */}
        <header className="bg-gray-900 text-white py-4">
  <nav className="container mx-auto flex justify-between items-center">
    <ul className="flex space-x-6">
      <li>
        <a href="/home" className="font-semibold hover:text-gray-400">
          Trang Chủ
        </a>
      </li>
      <li>
        <a href="/information" className="font-semibold hover:text-gray-400">
          Nội Dung
        </a>
      </li>
      {/* Mục Liên Kết với Dropdown */}
      <li className="relative group">
        <a href="#" className="font-semibold hover:text-gray-400">
          Download
        </a>
        <ul className="absolute left-0 hidden group-hover:block bg-gray-800 text-white mt-2 w-40 rounded shadow-lg">
          <li>
            <a
              href="https://www.youtube.com/@litn_dat"
              className="block px-4 py-2 text-lg hover:bg-gray-700 focus:outline-none"
            >
              Youtube
            </a>
          </li>
          <li>
            <a
              href="https://drive.google.com/drive/folders/1Wh5yXRV0VGKlOJkiqagxDhXAaRK1Zd4t?usp=sharing"
              className="block px-4 py-2 text-lg hover:bg-gray-700 focus:outline-none"
            >
              PDF
            </a>
          </li>
          <li>
            <a
              href="https://github.com/eagle-nett/ThuatToanMaHoa_Twofish"
              className="block px-4 py-2 text-lg hover:bg-gray-700 focus:outline-none"
            >
              Source Code
            </a>
          </li>
        </ul>
      </li>
      <li>
        <a href="/contact" className="font-semibold hover:text-gray-400">
          Liên Hệ
        </a>
      </li>
    </ul>
  </nav>
</header>


        {/* Nội dung */}
        <main className="container mx-auto py-10 px-4">{children}</main>

        

 <footer className="bg-gray-800 text-white py-4">
          <div className="container mx-auto text-center">
            <p>&copy; 2024 Website Twofish. All rights reserved.</p>
            <p>Made with ❤️  by Tien Dat, Quoc Anh, Dang Khoa</p>
          </div>
          
        </footer>
 
        
      </body>
    </html>
  );
}